config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      # TODO: refactor this block
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end

      resources :users, only: [:index, :show, :create, :update] do
        member do
          put :follow, :unfollow, :block, :unblock, :accept_request, :reject_request
          post :change_password
        end
        collection do
          get :top_users, :social_net_worth
          get :followers, :following, :pending_requests
          get :reset_password
        end
      end

      resources :notifications, only: :index

      resources :posts, except: [:new, :edit] do
        member do
          get :like, :unlike
        end
        collection do
          get :following_posts, :hashtag_posts, :top_posts, :tranding_tags
        end
        resources :comments, except: [:new, :edit]
        resources :comments_giphies, except: [:new, :edit]
        resources :reports, only: [:create]
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Notifications::Engine => "/notifications"
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',  }

  resources :users do
    member do
      get :following, :followers
      get "messages"
      put :block, :unblock
    end
    collection do
      get :search
      put :change_password
      post "create_message"
      get :suggested_username, :messages_users
    end
  end

  resources :relationships, only: [:create, :destroy] do
    member do
      put :accept, :reject
    end
    collection do
      post :add_to_circle
    end
  end

  resources :posts do
    member do
      put :toggle_vote
    end
  	collection do
	    get 'search'
    end
    resources :comments
    resources :reports, only: [:create]
  end

  resources :activities

  resources :giphy, only: [:index]

  resources :comment_giphies, only: [:destroy, :create]

  root 'pages#index'

  get '/home' => 'pages#home'
  get '/social_net_worth' => 'pages#social_net_worth'
  get '/user/:id' => 'pages#profile'

  get '/explore' => 'pages#explore'

  get '/load_more' => 'pages#load_more'
  get '/test' => 'pages#test'
  get '/tags/:hashtag' => 'pages#tags'
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :conversations do
    resources :messages
    collection do
      get :unread_conversation_messages
      put :mark_read
    end
  end

  # get "*path", to: redirect('/')
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!

  layout false

  def create
    @conversation_exist = false
    params[:sender_id] = current_user.id if params[:add_current_user].present?
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation_exist = true
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    @message = Message.new
    respond_to do |format|
      format.js
      format.json { render json: { conversation_id: @conversation.id } }
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  def unread_conversation_messages
    conversation_ids = Conversation.where('recipient_id = ? OR sender_id = ?', current_user.id, current_user.id).pluck(:id)
    unread_count = Message.where(conversation_id: conversation_ids, read: false).where.not(user_id: current_user.id).count
    render json: { unread_count: unread_count }
  end

  def mark_read
    if params[:conversation_id].to_s == '0'
      conversation_ids = Conversation.where('recipient_id = ? OR sender_id = ?', current_user.id, current_user.id).pluck(:id)
    else
      conversation_ids = params[:conversation_id]
    end
    Message.where(conversation_id: conversation_ids, read: false).where.not(user_id: current_user.id).update_all(read: true)
    ids = Conversation.where('recipient_id = ? OR sender_id = ?', current_user.id, current_user.id).pluck(:id)
    unread_count = Message.where(conversation_id: ids, read: false).where.not(user_id: current_user.id).count
    render json: { unread_count: unread_count }
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li class="conversation-li bounceInDown active" data-cid="<%= conversation.id %>">
  <%= link_to messages_user_path(current_user.id,{:conversation_id=>conversation.id}),:remote=>true do%>
    <img src="<%= conversation.sender_id == current_user.id ? conversation.recipient.avatar.url : conversation.sender.avatar.url%>" alt="" class="img-circle">
    <div class="friend-name">
      <strong><%= conversation.sender_id == current_user.id ? conversation.recipient.username : conversation.sender.username%></strong>
    </div>
    <% if conversation.messages.last %>
      <div class="last-message text-muted"><%= conversation.messages.last.body%></div>
      <small class="time text-muted"><%= conversation.messages.last.created_at_convert_timezone(current_user.timezone).to_formatted_s(:short) %></small>
    <% end %>
  <%end%>
</li>

app/views/conversations/create.js.erb
if ("<%= @conversation_exist %>" == "false") {
  $(".friend-list li:first").after('<%= j (render 'conversations/conversation', conversation: @conversation) %>')
  $('.conversation-message-block').html('<%= j (render 'users/conversation', conversation: @conversation) %>')
}

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.username %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa  fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <%= form_for([@conversation, @message], remote: true, :html => {id: "conversation_form_#{@conversation.id}", multipart: true}) do |f| %>
    <div class='form-group'>
      <div class='inline-block'>
        <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
      </div>
      <div class='pull-right inline-block'>
        <%= f.submit 'Send', class: 'btn btn-primary send-button' %>
      </div>
    </div>
    <%= f.file_field :attachment, id: "attachment_#{@conversation.id}" %>
  <% end %>
</div>

<%= subscribe_to conversation_path(@conversation) %>

<script type="text/javascript">
  $(document).ready(function(){
    $('#attachment_<%= @conversation.id %>').bind('change', function() {
      var FileSize = this.files[0].size / 1024 / 1024; // in MB
      if (FileSize > 1) {
        alert('File size exceeds 1 MB');
        $(this).val('');
      }
    });
  });
</script>