config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do

      # TODO: refactor this block
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end

      resources :users, only: [:index, :show, :create, :update] do
        member do
          put :follow, :unfollow, :block, :unblock, :accept_request, :reject_request
          post :change_password
        end
        collection do
          get :top_users, :social_net_worth
          get :followers, :following, :pending_requests
          get :reset_password
        end
      end

      resources :notifications, only: :index

      resources :posts, except: [:new, :edit] do
        member do
          get :like, :unlike
        end
        collection do
          get :following_posts, :hashtag_posts, :top_posts, :tranding_tags
        end
        resources :comments, except: [:new, :edit]
        resources :comments_giphies, except: [:new, :edit]
        resources :reports, only: [:create]
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Notifications::Engine => "/notifications"
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',  }

  resources :users do
    member do
      get :following, :followers
      get "messages"
      put :block, :unblock
    end
    collection do
      get :search
      put :change_password
      post "create_message"
      get :suggested_username, :messages_users
    end
  end

  resources :relationships, only: [:create, :destroy] do
    member do
      put :accept, :reject
    end
    collection do
      post :add_to_circle
    end
  end

  resources :posts do
    member do
      put :toggle_vote
    end
  	collection do
	    get 'search'
    end
    resources :comments
    resources :reports, only: [:create]
  end

  resources :activities

  resources :giphy, only: [:index]

  resources :comment_giphies, only: [:destroy, :create]

  root 'pages#index'

  get '/home' => 'pages#home'
  get '/social_net_worth' => 'pages#social_net_worth'
  get '/user/:id' => 'pages#profile'

  get '/explore' => 'pages#explore'

  get '/load_more' => 'pages#load_more'
  get '/test' => 'pages#test'
  get '/tags/:hashtag' => 'pages#tags'
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  resources :conversations do
    resources :messages
    collection do
      get :unread_conversation_messages
      put :mark_read
    end
  end

  # get "*path", to: redirect('/')
end

app/views/shared/_edit_delete_buttons.html.erb
<% if current_user %>
  <div id="manage_button_id_<%= post.id %>">
    <div class="top_icons">
      <% if can? :update, post %>
        <a href="javascript:void(0)" onclick="post_edit_mode(<%= post.id %>)">
          <i class="fa fa-pencil" aria-hidden="true"></i>
        </a>
      <% end  %>
      <% if can? :destroy, post %>
        <a href="javascript:void(0)" onclick="deletePost(<%= post.id %>)">
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        </a>
      <% end  %>
      <% if current_user.id != post.user_id && !post.reports.map(&:user_id).include?(current_user.id) %>
        <a href="javascript:void(0)" onclick="reportPostDialog(<%= post.id %>)">
          <i class="fa fa-flag" aria-hidden="true"></i>  
        </a>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <% if message.is_a? Array %>
      <%= message.join('\n') %>
    <% else %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function () {
    setTimeout(function() {
      $(".alert").alert('close');
    }, 5000);
  })
</script>

app/views/shared/_post_edit_mode.html.erb
<p id="post_view_id_<%= post.id %>" title="<%= raw post.content.gsub(/#([A-z]\w+)/, "<a href='/tags/\\1'>#\\1</a>") %>"><%= raw post.content.gsub(/#([A-z]\w+)/, "<a href='/tags/\\1'>#\\1</a>") %></p>
<div class="post_desc_edit" id="post_edit_id_<%= post.id %>" style="display: none;">
  <textarea id="post_content_edit_id_<%= post.id %>"><%= post.content %></textarea>
  <i class="fa fa-floppy-o" aria-hidden="true" onclick="update_post(<%= post.id %>)"></i>
  <i class="fa fa-ban" aria-hidden="true" onclick="post_view_mode(<%= post.id %>)"></i>
  <!--<button class='btn btn-primary' onclick="update_post(<%= post.id %>)">Save</button>-->
  <!--<button class='btn btn-danger' onclick="post_view_mode(<%= post.id %>)">Cancel</button>-->
</div>

app/views/shared/_report_post_dialog.html.erb
<div id="reportPost" class="modal fade" role="dialog" post-id="">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Report A Post</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <label for="comment">Comment:</label>
          <textarea class="form-control" rows="5" id="report_description"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" onClick='reportPost()'>Report</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_suggested_friends.html.erb
<% if users.present? %>
  <div class="widget">
    <div class="widget-header">
      <h3 class="widget-caption">People You May Know</h3>
    </div>
    <div class="widget-body bordered-top bordered-red">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <% users.each do |user| %>
              <div class="col-sm-12">
                <div class="panel">
                  <div class="panel-body p-t-10">
                    <div class="media-main">
                      <%= link_to(image_tag(user.avatar_url, class: "thumb-lg img-circle bx-s"), "/user/#{user.username}", class: "pull-left") %>
                      <div class="pull-right btn-group-sm">
                        <%= link_to relationships_path(followed_id: user.id), method: :post do %>
                          <i class="fa fa-user"></i>
                        <% end %>
                      </div>
                      <div class="info">
                        <h4><%= user.username %></h4>
                        <p class="text-muted"><%= user.email %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_top_posts.html.erb
<div class="panel">
  <div class="user-heading panel">
    <h1>Top Posts</h1>
  </div>
  <ul class="nav nav-pills nav-stacked">
    <% @top_posts.each do |post| %>
      <li>
        <a class="openmode" id="like<%=post.id%>" data-post="<%= post.id%>" data-status="like"><span aria-hidden="true"><%= raw post.content %></span></a>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_tranding_tags.html.erb
<% if hashtags.present? %>
   <div class="widget">
    <div class="widget-header">
      <h3 class="widget-caption">What's Trending</h3>
    </div>
    <div class="widget-body bordered-top bordered-red">
      <div class="card">
        <div class="content">
          <ul class="list-unstyled team-members">
            <% hashtags.each do |hashtag| %>
              <li>
                <div class="row">
                  <div class="col-xs-12 text-center">
                    <%= link_to hashtag.name, "/tags/#{hashtag.name}" %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>